customCommands:
  - key: "b"
    command: "git remote prune origin"
    context: "remotes"
    loadingText: "Pruning..."
    description: "prune deleted remote branches"
  - key: "<c-a>"
    command: "git absorb --and-rebase"
    context: "commits"
    loadingText: "Absorbing changes..."
    subprocess: true
    description: "Absorb changed files into past commits"
  - key: "o"
    context: "localBranches"
    prompts:
      - type: 'input'
        title: 'Title'
    command: "glab mr create --draft -b main --remove-source-branch -t \"{{index .PromptResponses 0}}\" -a sha512sum"
    subprocess: true
    description: "Create draft merge request from current branch"
  - key: "O"
    context: "localBranches"
    prompts:
      - type: 'input'
        title: 'Title (creating non-draft merge request)'
    command: "glab mr create -b main --remove-source-branch -t \"{{index .PromptResponses 0}}\" -a sha512sum"
    subprocess: true
    description: "Create draft merge request from current branch"

git:
  paging:
    colorArg: always
    pager: delta --dark --paging=never -n --keep-plus-minus-markers
gui:
  theme:
    selectedLineBgColor:
      - reverse
    selectedRangeBgColor:
      - reverse
    unstagedChangesColor:
      - blue
  showRandomTip: false
  showCommandLog: false
notARepository: 'skip'
os:
  openCommand: 'nvim {{filename}}'
