customCommands:
  - key: "b"
    command: "git remote prune origin"
    context: "remotes"
    loadingText: "Pruning..."
    description: "prune deleted remote branches"
  - key: "<c-a>"
    command: "git absorb --and-rebase"
    context: "commits"
    loadingText: "Absorbing changes..."
    subprocess: true
    description: "Absorb changed files into past commits"
  - key: "M"
    command: "git diff --name-only {{.SelectedLocalCommit.Sha}} && read -n1"
    context: "commits"
    subprocess: true
    description: "See files modified since commit"
  - key: "R"
    context: "tags"
    prompts:
      - type: 'input'
        title: 'version'
      - type: 'input'
        title: 'changelog file'
        initialValue: '/home/piotr/temp/changelog'
    command: "glab release create {{index .PromptResponses 0}} -r main -F \"{{index .PromptResponses 1}}\""
    subprocess: true
    description: "Create new release from main branch"
git:
  paging:
    colorArg: always
    pager: delta --dark --paging=never -n --keep-plus-minus-markers
gui:
  theme:
    selectedLineBgColor:
      - reverse
    unstagedChangesColor:
      - blue
    selectedRangeBgColor:
      - reverse
  showRandomTip: false
  showCommandLog: false
  showBottomLine: false
  showIcons: false
notARepository: 'skip'
os:
  open: 'nvim {{filename}}'
promptToReturnFromSubprocess: false

